spring.application.name=travel_agency

spring.datasource.url=jdbc:postgresql://localhost:5432/tour_agency_db
spring.datasource.username=postgres
spring.datasource.password=artemail
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=1
spring.security.user.password=1
spring.security.user.roles=ADMIN

spring.jpa.show-sql=false

server.port=8081

