spring.application.name=travel_agency
spring.datasource.url=jdbc:postgresql://localhost:5432/tour_agency_db
spring.datasource.username=postgres
spring.datasource.password=artemail
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=1
spring.security.user.password=1
spring.security.user.roles=ADMIN
spring.jpa.show-sql=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB